// GENERATED by scripts/build-image-variants.mjs — do not hand-edit.
//
// Real intrinsic dimensions and the responsive widths available for each image.
// PageHero uses these to emit a correct width/height (so the browser reserves
// the RIGHT box and does not shift) and a srcset (so a phone fetches a phone
// -sized file). Regenerate with: node scripts/build-image-variants.mjs
export interface ImageMeta { w: number; h: number; variants: number[] }

export const imageMeta: Record<string, ImageMeta> = {
  "about.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "athens-ga.webp": {
    "w": 1600,
    "h": 1063,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "atlanta-skyline.webp": {
    "w": 1600,
    "h": 899,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "buckhead.webp": {
    "w": 1600,
    "h": 1066,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "cleaning.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "decatur.webp": {
    "w": 1600,
    "h": 1200,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "dynamic-pricing.webp": {
    "w": 1600,
    "h": 900,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "georgia-city.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "georgia-coast.webp": {
    "w": 1600,
    "h": 1000,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "guest-experience.webp": {
    "w": 1600,
    "h": 2827,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "hero-home.webp": {
    "w": 1400,
    "h": 2100,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "hero-projection.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "inman-park.webp": {
    "w": 1400,
    "h": 1867,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "lake-lanier.webp": {
    "w": 1600,
    "h": 2400,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "metro-atlanta.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "midtown.webp": {
    "w": 1600,
    "h": 874,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "neighborhood-default.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "north-georgia.webp": {
    "w": 1600,
    "h": 2850,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "og-default.webp": {
    "w": 1200,
    "h": 630,
    "variants": [
      480,
      768
    ]
  },
  "old-fourth-ward.webp": {
    "w": 1400,
    "h": 933,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "owner.webp": {
    "w": 1400,
    "h": 2100,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "photography.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "savannah.webp": {
    "w": 1600,
    "h": 1060,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "service-management.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "suburb-home.webp": {
    "w": 1600,
    "h": 1067,
    "variants": [
      480,
      768,
      1200
    ]
  },
  "world-cup.webp": {
    "w": 1600,
    "h": 1200,
    "variants": [
      480,
      768,
      1200
    ]
  }
};

/** Intrinsic size for a /images/... src, or null when unknown. */
export function metaFor(src: string): ImageMeta | null {
  const file = src.split('/').pop() || '';
  return imageMeta[file] ?? null;
}

/** srcset for a /images/... src, or '' when no variants exist. */
export function srcsetFor(src: string): string {
  const m = metaFor(src);
  if (!m || !m.variants.length) return '';
  const stem = src.replace(/\.webp$/, '');
  return [...m.variants.map((w) => `${stem}-${w}.webp ${w}w`), `${src} ${m.w}w`].join(', ');
}
